name: EurekaApi CD

on:
  push:
    branches:
      - prod
      - dev
      - homolog

jobs:
  EurekaApiCD:
    environment: 
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
            role-session-name: github-action

      - name: Setting Stack and Repository name
        run: |
          echo "STACK_NAME=EurekaApi${{ github.ref_name }}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=eureka-api-repository${{ github.ref_name }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          cd iac
          pip install -r requirements.txt

      - name: Pushing Docker image to AWS ECR repository
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS  --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          docker build -t ${{ env.REPOSITORY_NAME }} .
          docker tag ${{ env.REPOSITORY_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.REPOSITORY_NAME }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.REPOSITORY_NAME }}:latest

      - name: Deploying CDK
        run: |
          cd iac
          cdk synth
          cdk deploy --require-approval never
        env:
          AWS_REGION: us-east-1
          STACK_NAME: ${{ env.STACK_NAME }}
          STAGE: ${{ github.ref_name }}
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}

